# Generated by Django 4.2.5 on 2023-10-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='name',
            field=models.CharField(help_text='Enter the type of work ', max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='View',
            field=models.ManyToManyField(help_text='Type of work', to='catalog.view'),
        ),
        migrations.AlterField(
            model_name='work',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='work',
            name='summary',
            field=models.TextField(help_text='Description', max_length=1000),
        ),
    ]
